/**
 * Java to Bedrock block id mapping
 */
export const blockIdsMap = new Map<string, string>()
    .set("minecraft:cave_air", "minecraft:air")
    .set("minecraft:void_air", "minecraft:air")
    .set("minecraft:bricks", "minecraft:brick_block")
    .set("minecraft:note_block", "minecraft:noteblock")
    .set("minecraft:creeper_wall_head", "minecraft:creeper_head")
    .set("minecraft:dragon_wall_head", "minecraft:dragon_head")
    .set("minecraft:piglin_wall_head", "minecraft:piglin_head")
    .set("minecraft:piston_head", "minecraft:piston_arm_collision")
    .set("minecraft:player_wall_head", "minecraft:player_head")
    .set("minecraft:zombie_wall_head", "minecraft:zombie_head")
    .set("minecraft:black_bed", "minecraft:bed")
    .set("minecraft:blue_bed", "minecraft:bed")
    .set("minecraft:brown_bed", "minecraft:bed")
    .set("minecraft:cyan_bed", "minecraft:bed")
    .set("minecraft:gray_bed", "minecraft:bed")
    .set("minecraft:green_bed", "minecraft:bed")
    .set("minecraft:light_blue_bed", "minecraft:bed")
    .set("minecraft:light_gray_bed", "minecraft:bed")
    .set("minecraft:lime_bed", "minecraft:bed")
    .set("minecraft:magenta_bed", "minecraft:bed")
    .set("minecraft:orange_bed", "minecraft:bed")
    .set("minecraft:pink_bed", "minecraft:bed")
    .set("minecraft:purple_bed", "minecraft:bed")
    .set("minecraft:red_bed", "minecraft:bed")
    .set("minecraft:white_bed", "minecraft:bed")
    .set("minecraft:yellow_bed", "minecraft:bed");
