name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test_cli:
    runs-on: ubuntu-latest
    name: CLI
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip" # caching pip dependencies

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - run: unzip assets/vanilla_structures.zip -d structures

      - run: python __main__.py
      
  test_regolith_filter:
    runs-on: ubuntu-latest
    name: Regolith Filter
    defaults:
      run:
        working-directory: './regolith-test-project'
    steps:
      - uses: actions/checkout@v4

      - name: Run Regolith
        uses: Bedrock-OSS/regolith-action@v1.5.0
        with:
          profile: default